Numpy Matrix

In [5]:
import numpy as np

Creating a matrix

In [6]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


If we want to create a matrix of 1000+ rows and columns then we can use obj.ones function and can provide columns value

In [8]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [9]:
mx_1s.dtype

dtype('float64')

To create a matrix of rows and columns use obj.ones and give values in tuple (row,column)

In [10]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


till now we are getting values in float and if we want to get value in int we need to provide dtype=int

In [18]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


if we want all values as zeros then we need to use obj.zeros

In [14]:
mx_0s=np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


if we need boolean values we can provide dtype as bool and 0s represent false and 1s represent true

In [15]:
mx_0s=np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [19]:
mx_1s=np.ones((3,4),dtype=bool)
print(mx_1s)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
mx_1s=np.ones((3,4),dtype=str)
print(mx_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


If we try to convert zero values into str then we get empty string

In [22]:
mx_0s=np.zeros((4,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


We can use bool as it will convert empty string to boolean value

In [24]:
empty_str=""
print(bool(empty_str))

False


to create an empty matrix we can use obj.empty but output will not necessarily contain zero values

In [25]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.62047965e-321]
 [1.42598117e-311 1.42598117e-311 9.82778786e-310]]
