Numpy Array slicing(:)

In [1]:
import numpy as np

In [2]:
mx=np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


To get a specific value we need to provide row and column position

In [26]:
mx[1,4]

TypeError: list indices must be integers or slices, not tuple

In [20]:
mx[0]

0

In [21]:
mx[:,0]

TypeError: list indices must be integers or slices, not tuple

In [25]:
mx[:,0:1]

TypeError: list indices must be integers or slices, not tuple

W3 SHCOOLS TUTORIALS

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])


Slice elements from index 1 to index 5 from the following array:

In [28]:
print(arr[1:5])

[2 3 4 5]


Slice elements from index 4 to the end of the array:

In [29]:
print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4 (not included):

In [31]:
print(arr[:4])

[1 2 3 4]


Negative Slicing


Use the minus operator to refer to an index from the end:

In [32]:
print(arr[-3:-1])

[5 6]


STEP

Use the step value to determine the step of the slicing:

In [34]:
print(arr[1:5:2])

[2 4]


In [35]:
print(arr[::2])

[1 3 5 7]


Slicing 2-D Arrays

In [37]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Here we are taking 1st row by providing 0 so it will do slicing accordingly

In [51]:
print(arr1[0,1:4])

[2 3 4]


In [41]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
print(arr1[1,1:4])

[7 8 9]


Here it will consider the column and as we hav provided [0:2] so it will take both rows

In [44]:
print(arr1[0:2,2])

[3 8]


In [47]:
print(arr1[0:2,3])

[4 9]


since it is [0:1] so it will take only one row of column which has index value 3

In [49]:
print(arr1[0:1,3])

[4]


In [53]:
print(arr1[0:2,1:4])

[[2 3 4]
 [7 8 9]]
