Numpy Functions

In [4]:
import numpy as np

arange() function provides a range syntax arange(start, end, step)

In [5]:
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


To create even array provide step value as 1

In [12]:
even_ar=np.arange(0,13,2)
print(even_ar)

[ 0  2  4  6  8 10 12]


using linspace() we can get difference between values

In [20]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

We can convert arrays into another dimension arrays using reshape(). Here above array was in one dimension and now it is converted into two dimension array

In [23]:
arr_2d=arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
arr_2d=arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


To convert 1d array into 3d array we need to provide values in sequential manner eg obj.reshape(3d value, 2d value, 1d value), also need to make sure the dot product of the array should match with the number of values present in 1d array.

In [25]:
arr_3d=arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [34]:
arr_11d=np.arange(1,19)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
arr_3d=arr_11d.reshape(2,3,3)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [39]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ravel() converts multidimension array into one dimension array

In [40]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten() converts multidimension array into one dimension array but we can get output in certain orders by using order="C","F","A","K"

In [46]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
ar.flatten(order="C")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
ar.flatten(order="F")

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

In [52]:
ar.flatten(order="A")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
ar.flatten(order="K")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

transpose() converts rows into columns here rows are 6 and columns are 2 became opposite of wht we had up

In [54]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

WE can even use obj.T for making use of transpose function

In [55]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])