Random sampling with numpy

If we need random data for ML/DL projects like otp generation we can use random module

In [8]:
import numpy as np
import random 

To create random values we need to use .random and it will only give values between 0 to 1

In [10]:
np.random.random(1)

array([0.86814545])

In [12]:
np.random.random((3,3))

array([[0.06367609, 0.27178235, 0.3533271 ],
       [0.72172766, 0.66522847, 0.17530134],
       [0.67561524, 0.84724415, 0.64501924]])

To get a value in single integer type we can use randint where 1 is starting point and 4 is ending point

In [19]:
np.random.randint(1,4)

2

We can create 2-D array using randint by providing range and shape

In [20]:
np.random.randint(1,4,(4,4))

array([[2, 2, 1, 3],
       [2, 1, 3, 1],
       [3, 2, 3, 2],
       [2, 1, 3, 2]])

Here for creating 3-D array we have given value as 2 for creating two arrays

In [21]:
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 3, 1],
        [3, 3, 1, 3],
        [3, 3, 3, 3],
        [3, 3, 1, 1]],

       [[3, 3, 3, 2],
        [1, 2, 1, 3],
        [1, 1, 3, 1],
        [2, 3, 1, 1]]])

when we use randint it gives us diff values all the time but if we want to use same values then we can use seed function.

In [23]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [26]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

We can create N-D array using rand function

In [27]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [28]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

randn gives us negative values

In [30]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

If we want to choose a rando number from a seqence we can use choice function

In [31]:
x=[1,2,3,4]

In [32]:
np.random.choice(x)

1

In [33]:
np.random.choice(x)

1

In [34]:
for i in range(20):
    print(np.random.choice(x))

1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3


In [35]:
x

[1, 2, 3, 4]

In [36]:
np.random.permutation(x)

array([2, 4, 1, 3])

In [37]:
np.random.permutation(x)

array([2, 3, 4, 1])