Numpy pract 1

In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


To check whether its array or list use type function

In [4]:
type(arr_1d)

numpy.ndarray

To check the dimension of array we need to use ndim

In [5]:
arr_1d.ndim

1

In [8]:
arr_2d=np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
arr_2d.ndim

2

To check size of array use obj.size

In [10]:
arr_2d.size

9

to check how many rows and columns r present use obj.size...(row,column)

In [11]:
arr_2d.shape

(3, 3)

to check integer type value in array use this

In [12]:
arr_2d.dtype

dtype('int32')